### ISSUE TITLE
webpack-dev-server cannot get port

### ISSUE THREAD

**Issue by amandaXCY** [webpack-contrib/grunt-webpack#155] opened 2017-10-22 11:24 UTC
I'm run the environment：
* webpack-dev-server 2.9.3
* webpack 3.8.1

in  this webpack.config.js 
```
devServer:{
    contentBase: path.resolve(process.cwd(), "./dist/"),
    port: 9000,
    hot: true,
    publicPath: "/",
    open: true
}
```
I'm run webpack-dev-server ,output: 
``
Project is running at http://localhost:9000/
webpack output is served from /
```


but i use grunt-webpack, i run `grunt webpack-dev-server`，output:
```
Project is running at http://localhost/webpack-dev-server/
webpack output is served from /

```
can not get port;

in the require('webpack-dev-server/lib/util/createDomain');

this function createDomain has tow argument;

```
'use strict';

const url = require('url');
const internalIp = require('internal-ip');

module.exports = function createDomain(options, listeningApp) {
  const protocol = options.https ? 'https' : 'http';
  const appPort = listeningApp ? listeningApp.address().port : 0;
  const port = options.socket ? 0 : appPort;
  const hostname = options.useLocalIp ? internalIp.v4() : options.host;

  // use explicitly defined public url (prefix with protocol if not explicitly given)
  if (options.public) {
    return /^[a-zA-Z]+:\/\//.test(options.public) ? `${options.public}` : `${protocol}://${options.public}`;
  }
  // the formatted domain (url without path) of the webpack server
  return url.format({
    protocol,
    hostname,
    port
  });
};

```
in the [https://github.com/webpack-contrib/grunt-webpack/blob/master/tasks/webpack-dev-server.js](https://github.com/webpack-contrib/grunt-webpack/blob/master/tasks/webpack-dev-server.js)




```
const uri = createDomain(opts) + (opts.inline !== false || opts.lazy === true ? '/' : '/webpack-dev-server/');
```

**Comment by danez** [comment] 2017-10-27 19:40
Duplicate of #156

**Closed by danez** 2017-10-27 19:40 UTC
