### ISSUE TITLE
Passing command line arguments to the Webpack

### ISSUE THREAD

**Issue by jay-cz** [webpack-contrib/grunt-webpack#85] opened 2016-10-10 08:53 UTC
Hi,

there was similar question some time ago regarding this matter, but the person wanted just to use production flag and sorted that out.

I have some custom logic in webpack configuration, which depends on command-line arguments passed to webpack.

So my question is - is there any clean way how to do it with grunt-webpack plugin?

**Comment by danez** [comment] 2016-10-10 14:23
Can you give an example about which options of webpack are cli only and can not be set with grunt-webpack?

**Comment by jay-cz** [comment] 2016-10-12 12:36
It is not any webpack option, it is a custom CLI attribute, which is passed and then processed in the webpack.config with use of [yargs ](https://www.npmjs.com/package/yargs) plugin. Our application is build from Maven and we need to pass it some information through maven-frontend-plugin.

Passing custom arguments through command like seemed to be like a good approach when we used stand-alone webpack. But then we wanted to have also Grunt in place... and now I ended up here with question above ;)

**Comment by gotofritz** [comment] 2016-11-29 09:59
I also would like to know, for exactly the same reason - adding tools to the chain (in our case maven and jenkins) and we  need to add vars passed as CLI parameters further up the chain.

**Comment by danez** [comment] 2017-04-11 12:07
Here is the documentation of [grunt.option](https://gruntjs.com/api/grunt.option) which seems like is doing what you want. As grunt seems to allow custom arguments you might probably also be able to use yargs to parse them.
I'm closing this now, as not a bug.

**Closed by danez** 2017-04-11 12:07 UTC
Labels: question

**Comment by jensbodal** [comment] 2017-05-18 23:57
I have two different webpack configs that do different things based on whether it's a development environment or build environment.  

Currently I'm using this command:

```
webpack --watch --config app/webpack.config.js --context app --env.build=build
```

Which is then processed in `webpack.config.js` as:

```
module.exports = function(env) {
  if (env && env.build && env.build === 'build') {
    return require('./webpack-configs/webpack.build.js');
  }

  return require('./webpack-configs/webpack.local.js');
};
```

I was using some custom grunt `faithful-exec` tasks for local and build commands, but I'd like to move to this plugin if possible.  Is there anyway to pass the `env` argument to my main export function?  Or am I doing something really wrong by choosing which config to run in this way?
